-- Q1. What is the total revenue generated by male vs females?
SELECT gender,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer_data
GROUP BY (gender)
;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

Select customer_id, `purchase_amount_(usd)`
FROM customer_data
WHERE discount_applied = "Yes"  AND `purchase_amount_(usd)` >=( SELECT AVG(`purchase_amount_(usd)`)
FROM customer_data)
;


-- Q3. Which are the top 5 products with the highest  average review rating?

SELECT item_purchased, ROUND(AVG(review_rating)) AS average_product_rating
FROM customer_data
GROUP BY(item_purchased)
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amount between Starndard and Express Shipping.

SELECT shipping_type, ROUND(AVG(`purchase_amount_(usd)`))
FROM customer_data
WHERE shipping_type IN ("Standard","Express")
GROUP BY shipping_type;  


-- Q5. Do subscribe customers spend more? Compare average spend and Total revenue between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(`purchase_amount_(usd)`),2) AS average_spend ,
ROUND(SUM(`purchase_amount_(usd)`),2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;


-- Q6. Which products have the highest percentage of purchase discounts applied?
 
 SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_of_discounts_applied
 FROM customer_data
 GROUP BY item_purchased
 ORDER BY (pct_of_discounts_applied) DESC
 LIMIT 5
;  


-- Q7. Segmant customers into New, Returning, Loyal based on their total number of previous purchases, and show count of each segment. 
 
WITH customer_loyalty as(
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN "New" 
	WHEN previous_purchases = 2 AND 10 THEN "Returning"
	ELSE "Loyal"
	END AS customer_segmant
FROM customer_data
)
SELECT customer_segmant, COUNT(customer_segmant) AS number_of_customers
FROM customer_loyalty
GROUP BY customer_segmant;


-- Q8. What are the top 3 most purchase products within each category?
 
 WITH item_counts AS (
 SELECT category,
 item_purchased,
 COUNT(customer_id) AS total_orders,
 ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC) AS item_rank
 FROM customer_data
 GROUP BY category, item_purchased
 )
 SELECT item_rank,category, item_purchased, total_orders
 FROM item_counts
 WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers( more than 5 previous purchases) also likely to subscribe?
 
 SELECT subscription_status, 
 COUNT(customer_id) AS repeat_buyers
 FROM customer_data
 WHERE previous_purchases > 5
 GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT age_group, SUM(`purchase_amount_(usd)`) AS revenue_contributon
FROM customer_data
GROUP BY age_group
ORDER BY age_group;













